# Dependabot configuration for automated dependency updates
# Per spec.md: "Dependabot automatically creates pull requests to keep npm dependencies up to date"

version: 2
updates:
  # npm dependencies (pnpm-based project)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"  # 4 AM UTC
      timezone: "UTC"
    open-pull-requests-limit: 10

    # Group updates by dependency type
    groups:
      # Production dependencies
      dependencies:
        patterns:
          - "@11ty/eleventy"
          - "@x-govuk/govuk-eleventy-plugin"
          - "ajv"
          - "js-yaml"
          - "pino"
          - "prom-client"
          - "uuid"
        update-types:
          - "minor"
          - "patch"

      # Development dependencies
      devDependencies:
        patterns:
          - "@axe-core/playwright"
          - "@eslint/*"
          - "@playwright/test"
          - "@types/*"
          - "eslint"
          - "prettier"
          - "tsx"
          - "typescript"
          - "typescript-eslint"
          - "vitest"
        update-types:
          - "minor"
          - "patch"

    # Commit message prefix
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"

    # Labels for pull requests
    labels:
      - "dependencies"
      - "automerge"

    # Enable automatic rebasing
    rebase-strategy: "auto"

    # Ignore major version updates (require manual review)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

    # Target main branch
    target-branch: "main"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5

    commit-message:
      prefix: "chore(actions)"
      include: "scope"

    labels:
      - "dependencies"
      - "github-actions"

    rebase-strategy: "auto"
