pings:
  - name: example
    protocol: HTTP
    method: GET
    resource: http://example.com
    tags:
      - health
      - driving licences
      - roads
      - ministry of foo
    expected:
      status: 200
      text: '</html>'
  - name: example head
    tags:
      - health
      - justice
      - central government
      - example dept
    protocol: HTTPS
    method: HEAD
    resource: https://example.com
    expected:
      status: 200
  - name: example three
    protocol: HTTP
    method: POST
    resource: http://example.com
    payload: { 'test': 'testing' }
    headers:
      - name: client
        value: gds-healthchecker
    tags:
      - health
      - driving licences
      - roads
      - ministry of foo
    expected:
      status: 411
      text: '</HTML>'

  - name: example five
    protocol: HTTP
    method: GET
    resource: http://example.com
    tags:
      - health
    expected:
      status: 301
      headers:
        location: http://example.com/expected_redirect_url
