/**
 * Eleventy configuration
 * Per T018: Configure GOV.UK Eleventy Plugin for status monitoring
 *
 * @see {@link https://x-govuk.github.io/govuk-eleventy-plugin/}
 * @see {@link https://www.11ty.dev/docs/config/}
 */

import { govukEleventyPlugin } from '@x-govuk/govuk-eleventy-plugin';

export default function (eleventyConfig) {
  // Configure GOV.UK Eleventy Plugin
  eleventyConfig.addPlugin(govukEleventyPlugin, {
    // Header configuration
    header: {
      homepageUrl: '/',
      productName: 'GOV.UK service status', // Per CLAUDE.md requirements
    },

    // Footer configuration
    // Per CLAUDE.md: "No Crown logo until hosted on gov.uk domain"
    footer: {
      copyright: false, // Disable Crown copyright
      licence: 'mit', // MIT license per project LICENSE
    },

    // Page title suffix
    titleSuffix: 'GOV.UK service status',

    // Icons - use default GOV.UK icons from plugin
    icons: {
      mask: '/assets/rebrand/images/govuk-icon-mask.svg',
      shortcut: '/assets/rebrand/images/favicon.ico',
      touch: '/assets/rebrand/images/govuk-icon-180.png',
    },

    // Markdown configuration
    markdown: {
      headingPermalinks: false, // No permalink anchors needed for status page
      headingsStartWith: 'xl', // Start with largest heading size
    },

    // Templates - only enable what we need
    templates: {
      error404: true, // Include 404 page
      sitemap: true, // Include sitemap
      feed: false, // No RSS feed needed for status page
      searchIndex: false, // No search needed for status page
      tags: true, // Enable tags for service categorization per User Story 2
    },

    // Base URL (set via environment variable in production)
    url: process.env.SITE_URL || 'http://localhost:8080',

    // Custom stylesheets (none initially, plugin provides GOV.UK styles)
    stylesheets: [],
  });

  // Passthrough copy for static assets
  // Copy config.yaml to output for transparency
  eleventyConfig.addPassthroughCopy('config.yaml');

  // Copy any custom assets if they exist
  eleventyConfig.addPassthroughCopy({ 'assets/**/*': 'assets' });

  // Copy CSV history file to output
  eleventyConfig.addPassthroughCopy('history.csv');

  // Global data
  // Health check results will be loaded from _data/health.json
  // (generated by orchestrator before Eleventy build)

  // Configure directory structure
  return {
    // Template formats
    templateFormats: ['md', 'njk', 'html', '11ty.js'],

    // Markdown engine
    markdownTemplateEngine: 'njk',
    htmlTemplateEngine: 'njk',

    // Directory structure per plan.md
    dir: {
      input: '.', // Root directory
      includes: '_includes', // Templates, layouts, components
      data: '_data', // Data files (health.json)
      output: '_site', // Build output (before post-build inlining)
    },

    // Use Nunjucks as primary template engine per research.md
    // GOV.UK plugin uses Nunjucks for all layouts
  };
}
