openapi: 3.0.0
info:
  title: GOV.UK Public Services Status API
  version: 1.0.0
  description: API for the current status of GOV.UK public services.
paths:
  /status.json:
    get:
      summary: Get current service status
      description: Returns the current status of all monitored services.
      responses:
        '200':
          description: A JSON array of service status objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceStatus'
components:
  schemas:
    ServiceStatus:
      type: object
      properties:
        name:
          type: string
          description: The name of the service.
        status:
          type: string
          description: The current status of the service (PASS, DEGRADED, FAIL, THROTTLED).
        latency_ms:
          type: integer
          description: The latency of the last health check in milliseconds.
        last_check_time:
          type: string
          format: date-time
          description: The ISO 8601 timestamp of the last health check.
        tags:
          type: array
          items:
            type: string
          description: An array of tags associated with the service.
        http_status_code:
          type: integer
          description: The HTTP status code of the last health check.
        failure_reason:
          type: string
          description: The reason for the failure, if any.